name: Hola mundo

on: 
  workflow_dispatch: #ejecuci√≥n manul
  push:
    branches:
      - main
    paths:
      - 'WebAPI/**'
      - 'WebApiTest/**'
      - '.github/workflows/hola-mundo.yml'

  pull_request:
    branches:
      - main
jobs: 
  saludar:
    runs-on: ubuntu-latest
    steps: 
      - name: Muestra mensaje hola mundo
        run: echo "hola mundo, Felipe"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Listar los archivos del respositorio
        run: 
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos:"
          tree
      
